- osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
Redo, to keep standard formatting
> #125 adding support to change tile providers at runtime

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/OfflineTileProvider.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/FileBasedTileSource.java
- pom.xml
#140 adding the basics for user selectable offline map sources instead of everything that's available offline and online
> #140 adding the basics for user selectable offline map sources

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/BaseSampleFragment.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleInvertedTiles_NightMode.java
- osmdroid-android/src/main/java/org/osmdroid/api/IMapController.java
- osmdroid-android/src/main/java/org/osmdroid/views/MapController.java
- osmdroid-android/src/main/java/org/osmdroid/views/MapControllerOld.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/TilesOverlay.java
- osmdroid-third-party/src/main/java/org/osmdroid/google/wrapper/MapController.java
- pom.xml
> 133 night mode

- osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/DefaultOverlayManager.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/OverlayManager.java
I don't like the idea of extending List in OverlayManager interface much but it would be big refactoring.
> #154 Possibility to change the OverlayManager in MapView.

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleAnimatedZoomToLocation.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleMilitaryIcons.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleWithMinimapItemizedOverlayWithFocus.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleWithMinimapItemizedOverlayWithScale.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleLoader.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleWithMinimapItemizedoverlay.java
- OpenStreetMapViewer/src/main/res/values-de/strings.xml
- OpenStreetMapViewer/src/main/res/values-it/strings.xml
- OpenStreetMapViewer/src/main/res/values-it/tile_sources.xml
- OpenStreetMapViewer/src/main/res/values/strings.xml
- OpenStreetMapViewer/src/main/res/values/tile_sources.xml
- pom.xml
Completed testing with Java 1.7 changes. This includes updating the pom.xml target.
Many files modified to use diamond operators.
Also did a minor cleanup of strings.xml with translations
This branch was tested for compatibility with **gradle clean build** & **mvn clean install**
> Update to Java7

- osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
remove all the message in mTileRequestCompleteHandler.
> mTileRequestCompleteHandler remove message.

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/AsyncTaskDemoFragment.java
* fixed zoom update problem. 
* fixed: Stop running AsyncTask on view-destroy
* set initial map position
> #394 #398 pr398 fixed AsyncTaskDemoFragment.java

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/SimpleFastPointOverlay.java
For some reason this bug didn't happen before 5.6. This is just an emergency fix, but I need to better understand what's going on before this line, as this fix should not be needed, given the view bounding box test earlier in the code.
> Fixed array out of bounds bug

- OpenStreetMapViewer/src/main/res/layout/activity_main.xml
Removed padding from MainActivity for consistency of UI.
> Removed homepage padding

- .gitignore
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/ThunderforestTileSource.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java
This is working fine with me.  I added TileSourceFactory::removeTileSources() to keep the options list a bit smaller when adding several of the Thunderforest ones.
> Feature/#573 CycleMap

- GoogleWrapperSample/src/main/AndroidManifest.xml
- OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/Bug512CacheManagerWp.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloaderCustomUI.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java
* More flexible CacheManager
* Slight impact of CacheManager refactoring on the other 2 classes
* Slight correction on the manifest not related to #619 but needed when testing
> feature/#619 more flexible CacheManager

- osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java
- osmdroid-android/src/main/java/org/osmdroid/config/IConfigurationProvider.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileDownloader.java
> Support network proxy in Configuration

- OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/Bug445Caching.java
* Bug445Caching: more verbose and more accurate version
> Answer to failing checks:

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java
> Feature/pr657 Update CacheManager.java - Add Alert-Confirmation before canceling 

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/infowindow/InfoWindow.java
Adding this constructor allows views added programmatically instead of declared in an xml layout. I needed this constructor so that i can create a webview in an InfoWindow without using xml
> add constructor InfoWindow(View, Mapview)

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleLimitedScrollArea.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleExtensive.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleWithMinimapZoomcontrols.java
- osmdroid-android/src/main/java/org/osmdroid/util/BoundingBox.java
- osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
- osmdroid-android/src/main/java/org/osmdroid/views/Projection.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/OverlayLayoutParams.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/ZoomButtonsOverlay.java
- osmdroid-android/src/test/java/org/osmdroid/util/ProjectionTest.java
Fixed the bug, as far as I understand it (I just compared with an old version of the code).
> Bug/#745 Double-Tap-Zoom ignores location of zoom

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleLimitedScrollArea.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleExtensive.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleWithMinimapZoomcontrols.java
- osmdroid-android/src/main/java/org/osmdroid/util/BoundingBox.java
- osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
- osmdroid-android/src/main/java/org/osmdroid/views/Projection.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/OverlayLayoutParams.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/ZoomButtonsOverlay.java
Fixed, cf. demo "More Samples / Events / Limited scroll area"
> Bug/#742 ScrollableAreaLimit not working

- osmdroid-android/src/test/java/org/osmdroid/util/GeoPointTest.java
* `GeoPointTest`: added the notion of "minimum distance" under which
we dismiss the distance computations as they are prone to inaccuracy.
> #728: gentle fix of a unit test that (sometimes) crashed

- osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java
> Bug/#785 Fix calculation of max cache size and trim size with new db

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/DrawPolygonWithoutVerticalWrapping.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/DrawPolygonWithoutWrapping.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/PressToPlotWithoutWrapping.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/SampleDrawPolylineWithoutVerticalWrapping.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/SampleDrawPolylineWithoutWrapping.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/SampleAssetsOnlyRepetitionModes.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/SampleAssetsOnlyWithoutWrapping.java
- OpenStreetMapViewer/src/main/res/layout/layout_wrapping.xml
- osmdroid-android/src/main/java/org/osmdroid/util/TileLooper.java
- osmdroid-android/src/main/java/org/osmdroid/util/TileSystem.java
- osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
- osmdroid-android/src/main/java/org/osmdroid/views/Projection.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/TilesOverlay.java
- osmdroid-android/src/main/java/org/osmdroid/views/util/PathProjection.java
`MapView` now supports the configuration of the repetition in the horizontal and vertical direction:
* `setHorizontalMapRepetitionEnabled(boolean)`
* `setVerticalMapRepetitionEnabled(boolean)`
Issue: https://github.com/osmdroid/osmdroid/issues/787
> Feature/#787 Repetition Modes

- OpenStreetMapViewer/src/main/java/org/osmdroid/debug/browser/CacheAdapter.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/debug/model/SqlTileWriterExt.java
> bug/#862 Close Cursors after use

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/WeatherGroundOverlaySample.java
- osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/GroundOverlay2.java
This is a first cut, it works better than GroundOverlay (with midpoint) from the bonuspack.
> add GroundOverlay2

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/bing/BingMapTileSource.java
See https://github.com/osmdroid/osmdroid/issues/900#issuecomment-360743365
> Fix for #900

- osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java
- osmdroid-android/src/main/java/org/osmdroid/config/IConfigurationProvider.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileCache.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTilePreCache.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java
- osmdroid-android/src/main/java/org/osmdroid/util/GarbageCollector.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/TilesOverlay.java
- osmdroid-android/src/test/java/org/osmdroid/util/GarbageCollectorTest.java
Looks very smooth to me.
It should solve #812: @miguel-porto I think this time it's going to be good! ;)
Actually the code of #973 is included - which shouldn't be a problem.
> Feature/#930 - Async tile pre-caching

- gradle.properties
- osmdroid-android/build.gradle
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/IterableWithSize.java
- osmdroid-android/src/main/java/org/osmdroid/util/IterableWithSize.java
- osmdroid-android/src/test/java/org/osmdroid/tileprovider/cachemanager/CacheManagerTest.java
Do not calculate all the points for a bounding box in the CacheManagerTask constructor but rather retrieve them one by one.
> Feature/#977: Sometimes CacheManager#downloadAreaAsync too slow

- osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java
- osmdroid-android/src/main/java/org/osmdroid/config/IConfigurationProvider.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileCache.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTilePreCache.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java
- osmdroid-android/src/main/java/org/osmdroid/util/GarbageCollector.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/TilesOverlay.java
- osmdroid-android/src/test/java/org/osmdroid/util/GarbageCollectorTest.java
- osmdroid-android/src/test/java/org/osmdroid/views/overlay/LinearRingTest.java
... to be used in Polygon.setDefaultInfoWindowLocation
New class:
* `LinearRingTest`: unit test class for `LinearRing`, only testing method `getCenter` for the moment
* `LinearRing`: added method `getCenter`
> Bug/#979 - new LinearRing.getCenter method

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java
* `MyLocationNewOverlay`: got rid of the "projected" part; removed pointless and prone to bugs method `getMyLocationDrawingBounds`
> Bug/#987 - simplified the location display in order to avoid bugs

- OpenStreetMapViewer/src/main/java/org/osmdroid/PreferenceActivity.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/debug/model/SqlTileWriterExt.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/intro/StoragePreferenceFragment.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java
* `PreferenceActivity`: handled the case when the SD card is not available
* `StoragePreferenceFragment`: handled the case when the SD card is not available
> Bug/#999 - bug fix when the SD card is not available

- OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/Bug512CacheManagerWp.java
- OpenStreetMapViewer/src/main/res/layout/sample_cachemgr.xml
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java
> Bug/#1050 Switch mapnik tilesource to https

- OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/Bug419Zoom.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/SampleBug57.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/animations/AnimatedMarkerHandler.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/animations/AnimatedMarkerTypeEvaluator.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/animations/AnimatedMarkerValueAnimator.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/CacheImport.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/CachePurge.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDelete.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloader.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloaderArchive.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloaderCustomUI.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleZoomToBounding.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/layouts/pager/MapFragment.java
closes #1081 
switch to programmatically created mapviews in all fragments using the
layout "sample_cachemgr".
> Fix Bug in sample app

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileDownloader.java
* `CacheManager`, `MapTileDownloader`: added a setter for `TileDownloader mTileDownloader`
> feature/#1067 - Setter for classes using a TileDownloader

- osmdroid-android/src/main/java/org/osmdroid/views/Projection.java
* `Projection`: added comments to member `mProjectedMapSize` and method `public PointL getLongPixelsFromProjected(PointL, double, boolean, PointL)`
> bug/#992_2 - Added comments

- osmdroid-android/src/main/java/org/osmdroid/views/MapController.java
- osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
> bug/#1040_2 - calls to listeners for ScrollEvents in MapView.setExpectedCenter

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileApproximater.java
closes #1099 
Please review and probably test this, to make sure I didn't introduce some side-effect.
> Fix ConcurrentModificationException

- osmdroid-android/src/main/java/org/osmdroid/api/IMapController.java
- osmdroid-android/src/main/java/org/osmdroid/views/MapController.java
Impacted interface:
* `IMapController`: added a version of `animateTo` with an orientation parameter
* `MapController`: added a version of `animateTo` with an orientation parameter; gently refactored
> feature/#1119 - `MapController.animateTo` with an orientation parameter

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java
> bug/#1171 - Actually throw SQLiteFullException

- osmdroid-android/src/main/java/org/osmdroid/util/BoundingBox.java
> BoundingBox: Fix wrapping of longitude.

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMapSnapshot.java
- osmdroid-android/src/main/java/org/osmdroid/views/drawing/MapSnapshot.java
- osmdroid-android/src/main/java/org/osmdroid/views/drawing/MapSnapshotHandler.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/ScaleBarOverlay.java
New class:
* `SampleMapSnapshot`: displaying all USA states in a `RecyclerView`, using `MapSnapshot`s
* `MapSnapshot`: added member `mIsDetached` in order to have a cleaner "detach" operation
* `MapSnapshotHandler`: fixed a possible NPE
* `SampleFactory`: added sample "More Samples / Data / MapSnapshot RecyclerView" (`SampleMapSnapshot`)
* `ScaleBarOverlay`: created members `mMapWidth` and `mMapHeight` and their getters; created one public constructor (for `MapSnapshot`s) and one private constructor (used by both public constructors); gently refactored
> feature/#990_3 - displaying all USA states in a RecyclerView

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/BitmapTileSourceBase.java
Hi,
I am working with different tile sources for the same layer, that deliver different Resolution for the same tile.
I.e. I have a local renderer for a small extent, that is able to render at full DPI resolution (870x870 or something).
At the same time, I have an online source, that renders at a default 512x512 pixels when outside the area that is supported by the local renderer. Osmdroid automatically scales these smaller tiles up, if the tile-sources delivers tiles that are smaller than advertised (512 instead of 870px)
Everything works quite nicely, if the TileSource's mTileSizePixels is set to 870x870. The Tiles coming from the online source will automatically be scaled up and everything looks good. However, I noticed a memory leak:
If the mTileSizePixels doesn't actually match the …
> Fixed memory leak if the tile source's tile size doesn't actually match image size

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/util/CloudmadeUtil.java
Authentication service should be accessed via HTTPS.
> Change Cloudmade auth URL to HTTPS

- build.gradle
prevent mitm codeinjection
see https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb
> security fix

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleSnappable.java
...in "More Sample / Events / Snappable"
New class:
* `SampleSnappable`: demo for the "snap" feature, centered on the railway station of Perpignan
* `SampleFactory`: added the `SampleSnappable` demo
> bug/#1299_3 - demo for "Snappable" feature

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleSpeechBalloon.java
- osmdroid-android/src/main/java/org/osmdroid/util/MyMath.java
- osmdroid-android/src/main/java/org/osmdroid/util/RectL.java
- osmdroid-android/src/main/java/org/osmdroid/util/SpeechBalloonHelper.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/SpeechBalloonOverlay.java
- osmdroid-android/src/test/java/org/osmdroid/util/MyMathTest.java
- osmdroid-android/src/test/java/org/osmdroid/util/SpeechBalloonHelperTest.java
New classes:
* `SampleSpeechBalloon`: Demo around the new `SpeechBalloonOverlay` feature in "More Samples / Data / Speech Balloon"
* `SpeechBalloonHelper`: Helper class for `SpeechBalloonOverlay` that includes method `compute` which computes the intersection between a rectangle and the triangle that starts from a Point and goes to a circle centered on the rectangle's center
* `SpeechBalloonHelperTest`: Unit test class for `SpeechBalloonHelper`
* `SpeechBalloonOverlay`: Overlay that displays a title in a "speech balloon"
* `MyMath`: added methods `computeAngle` and `computeCirclePoint`
* `MyMathTest`: added methods `testComputeAngle` and `testComputeCirclePoint`
* `RectL`: added methods `centerX` and `centerY`
* `SampleFactory`: added a reference to new demo …
> feature/#1347 - SpeechBalloonOverlay

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java
> feature/#1400 - add DensityMultiplier to Polyline

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/Marker.java
> bug/#1452 - Draggable Marker disappear when changing longtitude

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/PolyOverlayWithIW.java
* `PolyOverlayWithIW`: created a `boolean isVisible(Projection)` method in order to skip unnecessary poly display attempts
> feature/#1465 - new isVisible(Projection) method for poly display

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBase.java
* `MapTileProviderBase`: created private methods `sendMessage` and `sendMessageFailFast` that deal with `ConcurrentModificationException`
> bug/#1446_2 - Concurrency exception management

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/compass/CompassOverlay.java
* `CompassOverlay`: added members `mLastRenderLag`, `mAzimuthPrecision` and their setters; impacted the rendering frequency accordingly; minor refactoring
> feature/#1498 - parameters in CompassOverlay regarding rendering frequency

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java
> bug/#1516 - Fixed URLs for HikeBikeMap

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/gridlines/LatLonGridlineOverlay2.java
* `LatLonGridlineOverlay2`: side-effects and performance fixes of the draw process (no object creation, no Polyline, no Marker, no FolderOverlay); minor refactoring; added zoom level values for the incrementor up to level 29
* `LinearRing`: granted a `public static` access to method `getCloserValue`
> bug/#1514 - side-effects and performance fixes of lat/lon grid display

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/OfflineTileProvider.java
* `OfflineTileProvider`: overriding method `isDowngradedMode`; minor refactoring
> bug/#1519 - OfflineTileProvider works definitely in a "downgraded mode"

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java
* `MyLocationNewOverlay`: now using `twotone_navigation_black_48`
> feature/#1530_2 - more visible icon for MyLocationNewOverlay

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/PolyOverlayWithIW.java
Impacted file:
* `PolyOverlayWithIW`
> bug/#1549 - more robust onDetach method for PolyOverlayWithIW

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java
> Allow multitouch events when enableAutoStop is false

- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/ShowAdvancedPolylineStylesInvalidation.java
- OpenStreetMapViewer/src/main/res/layout/layout_advanced_polyline_invalidate.xml
See #1576 
Edit: Invalidation working now.
> feature/#1576 - Additional samples with scalar invalidation from advanced polyline

- osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/TileDownloader.java
Keep old behaviour as fallback
fixes #1617
> Set TLS1.2 as the only protocol if supported

- .gitignore
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
Without reformarting all.
You should do this and commit all changes
> common codestyle

- osmdroid-android/src/main/java/org/osmdroid/views/overlay/CopyrightOverlay.java
Update license of file according to https://github.com/osmdroid/osmdroid/issues/1693#issuecomment-995530625
> update copyrightoverlay license header

- osmdroid-android/src/main/res/values/strings.xml
https://github.com/osmdroid/osmdroid/issues/1847
> fix for non-positional format of string resource

- OpenStreetMapViewer/src/main/java/org/osmdroid/StarterMapFragment.java
- osmdroid-android/src/main/java/org/osmdroid/views/overlay/gestures/OneFingerZoomOverlay.java
#1951 
Before:
https://github.com/osmdroid/osmdroid/assets/42921436/49d84d1f-4182-418a-9949-dd65fc99caf4
After:
https://github.com/osmdroid/osmdroid/assets/42921436/a551fe60-8dcc-490f-baa2-47520e33ec86
> #1951 add one-finger zoom

- OpenStreetMapViewer/src/main/java/org/osmdroid/OsmApplication.java
- OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/WeatherGroundOverlaySample.java
- osmdroid-android/src/main/java/org/osmdroid/tileprovider/util/StorageUtils.java
fixes urls for conus weather overlay
turns off strict mode for the debug build. it's constantly crashing
fixes a potentially open source stream from storage utils
> #2017  WeatherGroundOverlaySample no longer works

- README.md
a plea for support from the community to keep this repo alive
> Update README.md - adoption notice
