OpenStreetMapViewer/src/org/osmdroid/samplefragments/SampleWithMinimapItemizedOverlayWithFocus.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/OverlayItem.java
In my current osmdroid project i want to display gpx-trackpoint-items that are not inherited from class GeoPoint. This tiny change would make this possible by replacing reference to class GeoPoint with interface IGeoPoint.
=> Allow OverlayItem to be used by non-GeoPoint class

osmdroid-android/src/main/java/org/osmdroid/util/BoundingBoxE6.java
When a boundingbox spans the 180th meridian (anti-meridian), the contains method will fail.
Example: BoundingBoxE6(72.d, -128.d, 48.d, 170.d)
=> Bugfix: contains fails when boundingbox spans 180th meridian

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleAnimatedZoomToLocation.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java, osmdroid-android/src/main/java/org/osmdroid/api/IMapController.java, osmdroid-android/src/main/java/org/osmdroid/views/MapController.java, osmdroid-android/src/main/java/org/osmdroid/views/MapControllerOld.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-third-party/src/main/java/org/osmdroid/google/wrapper/MapController.java
Added an animated zoomTo() method as well as implemented it in the zoomToBoundingBox() by providing an animate flag.
The existing zoomIn() and zoomOut() methods call the new zoomToFixing() method.
Additionally, the ZoomAnimatorListener was renamed and now includes the @TargetApi() annotation which is required due to the listener only being available in a newer API.
=> Implemented Animated Zoom To ZoomLevel

OpenStreetMapViewer/build.gradle, OpenStreetMapViewer/src/main/AndroidManifest.xml, build.gradle, osmdroid-android/build.gradle, osmdroid-third-party/build.gradle, settings.gradle
Current project features a build error as it is unable to resolve **support:compatibility** in the **OpenStreetMapViewer\build.gradle**. This error is referenced in issue #194.
> Error:(32, 13) Failed to resolve: android.support:compatibility-v4:23+
This is resolved by replacing the dependency:
> compile 'android.support:compatibility-v4:23+'
with
> compile 'com.android.support:support-v4:23+'
=> Fixed gradle build error for support:compatibility 

OpenStreetMapViewer/build.gradle, OpenStreetMapViewer/src/main/AndroidManifest.xml, OpenStreetMapViewer/src/main/java/org/osmdroid/MapActivity.java, OpenStreetMapViewer/src/main/java/org/osmdroid/MapFragment.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleAnimatedZoomToLocation.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleJumboCache.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleOfflineOnly.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleLoader.java, OpenStreetMapViewer/src/main/res/layout/main.xml, OpenStreetMapViewer/src/main/res/layout/mapview.xml, OpenStreetMapViewer/src/main/res/values/strings.xml
Went through many files trying to clean up readability.
For SampleLoader, I cleaned up the permission system as it was requesting many permissions which are automatically granted. The project only requires two permission groups Location & Storage, helping simplify the sample code. In addition, I grouped AndroidManifest permissions into groups for easy understanding of permissions and expectations.
Updated deprecated code in MapActivity to be used directly inside its Fragment. (Dialog)
Updated build.gradle to match AndroidManifest.xml versioning.
Minor formatting cleanup in various files.
=> OSMapViewer Code Cleanup - Permissions and other fixes.

OpenStreetMapViewer/src/main/java/org/osmdroid/MainActivity.java
The former permission check implementation only checked for a single permission for each session. This new implementation will request both permissions on first launch. Additionally, I improved the workflow for a better user experience with an initial Toast to explain why they are being prompted for the permission.
Commit is a bit confusing. I moved the ListView choice selection to the top, and rewrote both permission methods from scratch.
[Travis CI states the build is passing](https://travis-ci.org/ZKjellberg/osmdroid/builds/100106300)
=> New Permission Check implementation

osmdroid-android-it/src/main/java/org/osmdroid/views/util/OpenStreetMapTileProviderDirectTest.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/BitmapTileSourceBase.java
It is more a question rather than a pull request.
Why the `getDrawable(String aFilePath)` does not throw an `LowMemoryException`?  It is to maintain compatibility somwhere?
It looks very strange. The [TileSource#getDrawable(String aFilePath)](https://github.com/illarionov/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/ITileSource.java#L54) allows to throw this exception.
=> Throw LowMemoryException on getDrawable(final String aFilePath)

README.md
The original README was a bit loud with headers. I revamped the README to merge multiple sections, removing the large spacing due to the many headers and integrated sections which served similar purpose causing repeat statements.
Two notes:
1. I see the latest commit reverted the title of the sample app to **Open Map**, shouldn't this maybe be **osmdroid**?
2. Is it necessary to include reference about the move from Google Code? It has been nearly two years since the move. Or rather would it be okay to at least unbold the text?
=> Revamped readme to be more concise.

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
`MapTileProviderBasic` is created with application context instead.
=> #250 fixed memory leak in NetworkAvailabliltyCheck

.travis.yml
I tried building locally and I did not get the compile problems you see on travis. So at least theoretically this should work
-B removes the log lines for KB download stuff
-U forces to check in upstream repo for artifacts
hth
=> using batchmode and adding updated flag for Maven builds

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
Add a boolean to pause fling during zoom changes and avoid untimely flings.
=> OSMDroid pinch to zoom sensitivity issue #269

GoogleWrapperSample/build.gradle, gradle.properties, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-third-party/build.gradle
Hi,
we needed for a project a custom projection class for our osmdroid mapview. This was currently not possible since the projection member of the map view was read only for derived classed and the reset of the projection was not done using a setter method (that could be overwritten).
So i did the following
* switched projection to be protected instead of private and added protected setter for projection in order to use own projection class
Also i updated the build tools to the current version of 23.0.3
I think there is no real reason for not providing write access to the projection member for derived classes. 
It would be nice if that could be merged into the main repo
=> Support implementation of own projection classes

osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileModuleProviderBase.java, osmdroid-forge-app/build.gradle, osmdroid-forge-app/src/main/java/org/osmdroid/forge/app/MainActivity.java, osmdroid-mapsforge/build.gradle, osmdroid-mapsforge/src/main/java/org/osmdroid/mapsforge/MapsForgeTileModuleProvider.java, osmdroid-mapsforge/src/main/java/org/osmdroid/mapsforge/MapsForgeTileSource.java
Changes:
* Fix: Added more temporary memory for rendering. See https://github.com/mapsforge/mapsforge/issues/868 for details
*  Added debuglogging to osmdroid-mapsforge code via OpenStreetMapTileProviderConstants.DEBUG_TILE_PROVIDERS==true
* Update to mapsforge-0.6.1
* Example app: Hide dependencies to mapsforge-version
Note i kept dependcy to kxml2
=> Mapsforge Adapter updates

osmdroid-android/src/main/java/org/osmdroid/views/overlay/DefaultOverlayManager.java
… overlay to be called twice, while code should not have executed on one of them, it caused duplicate loops as discussed in issue #440
=> Possible duplicate code in DefaultOverlayManager #440

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
zoomToBoundingBox  return corupted results cause of mistyping 186 instaed of 1e6
=> Fix Mapview zoomToBoundingBox 186 mistyping

osmdroid-android-it/src/main/java/org/osmdroid/tileprovider/modules/MapTileProviderTest.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBase.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileApproximater.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileAssetsProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileDownloader.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileFileArchiveProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileFilesystemProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileModuleProviderBase.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileSqlCacheProvider.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-geopackage/src/main/java/org/osmdroid/gpkg/GeoPackageMapTileModuleProvider.java, osmdroid-mapsforge/src/main/java/org/osmdroid/mapsforge/MapsForgeTileModuleProvider.java
`MapTileApproximater` now accepts not only one but several providers. They are added using new method `addProvider(final MapTileModuleProviderBase pProvider)`.
When `MapTileApproximater.getTileLoader().loadTile(MapTile mapTile)` is called, we return an approximation from the best possible bitmap, which comes from the best possible zoom level among all providers, and from the first provider on the ordered providers list for that best zoom level.
Files impacted:
* `MapTileApproximater`: changed the constructors, added method `addProvider(final MapTileModuleProviderBase pProvider)`, refactored `approximateTileFromLowerZoom`methods
* `MapTileModuleProviderBase`: `TileLoader` is more `public`, `getTileLoader()` is upgraded from `Runnable` to `TileLoader`, new method `loadTile(final MapTile …
=> feature/#646: MapTileApproximater with several sources

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
As discussed in the Issue report #693.
=> Fix for #693 - Relayout children when scrolling map and bugfix for wrong MapView.LayoutParams positioning

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/animations/MaximumZoomLevel.java, osmdroid-android/src/main/java/org/osmdroid/views/MapController.java
This PR fixes double tab zoom animation around maximum zoom for devices >= Honeycomb.
An example can be found in `Animations - Maximum Zoom Level`.
Issue: https://github.com/osmdroid/osmdroid/issues/743
=> #743: Fix double tab zoom animation around maximum zoom

OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/Bug419Zoom.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/animations/MaximumZoomLevel.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloader.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloaderArchive.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloaderCustomUI.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleOsmPath.java, osmdroid-android/src/main/java/org/osmdroid/api/IMapView.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-third-party/src/main/java/org/osmdroid/google/wrapper/MapView.java
`setMaxZoomLevel` and `setMinZoomLevel` now use `Double` instead of `Integer`.
Inside `CacheManager` the `double` are casted to `int`. I'm not sure this is the correct way to go though.
issue: https://github.com/osmdroid/osmdroid/issues/734
=> # Use double for maximum and minimum zoom level

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/animations/MinMaxZoomLevel.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
The pinch-zoom gesture now respects the minimum and maximum zoom. 
Previously it was possible to exceed the minimum and maximum zoom of the mapview  during a pinch-zoom. When the gesture was finished, the zoom snapped to the minimum and maximum zoom. Now the pinch-zoom respects the minimum and maximum zoom and does not allow to exceed these values even during the gesture.
The new behaviour can be tested via  the `MinMaxZoomLevel` sample.
Issue: https://github.com/osmdroid/osmdroid/issues/761
=> Bug/#761 Respect minimum and maximum zoom during pinch-zoom

osmdroid-android/src/main/java/org/osmdroid/util/SegmentClipper.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polygon.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java, osmdroid-android/src/test/java/org/osmdroid/util/SegmentClipperTest.java
* `LinearRing`: removed clip area limits constants; created methods `setClipArea` in order to set the most relevant clip area according to the current `MapView`
* `Polygon`: used new method `LinearRing.setClipArea(MapView)`
* `Polyline`: used new method `LinearRing.setClipArea(MapView)`
=> feature/#725 - computing the `LinearRing` clip area limits

osmdroid-android/src/main/AndroidManifest.xml
Removes the permissions from the library in order to not inflict them on developers.
Users of the library have to include them accordingly.
issue: https://github.com/osmdroid/osmdroid/issues/779
=> #779 Remove permissions from library

osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlay.java
This PR adds the zoom and scale of the map to the parameters of `ItemizedOverlay.onDrawItem(...)`. This allows subclasses to use this parameters for custom logic regarding drawing the icons.
issue: https://github.com/osmdroid/osmdroid/issues/781
=> #781 Add zoom and scale parameters in onDrawItem of ItemizedOverlay

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-android/src/main/java/org/osmdroid/views/Projection.java
* `MapView`: modified method `checkScrollableAreaBoundingBox` in order to take into account the current scale
* `Projection`: added member `Matrix mScaleMatrix` in order to deal with the scale factor without the rotation; added method `scalePoint` in order to apply `mScaleMatrix` to a point; added helper method `applyMatrixToPoint`
Bad news: the map angle isn't taken into account. The results with an angle do not look like a big bug but are not perfect.
I think that in general many things should be fixed regarding the map angle, including the MiniMap behavior. In another issue I guess...
=> bug/#762: taking the current scale into account

osmdroid-android-it/src/main/java/org/osmdroid/tileprovider/modules/MapTileProviderTest.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/IMapTileProviderCallback.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderArray.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBase.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileModuleProviderBase.java
Right now, when a tile can not be retrieved due to the max queue size being reached, the callback method `mapTileRequestFailed` is being called just like as if the corresponding provider doesn't have this tile. This is problematic, as `MapTileProviderArray` is then looking for the next appropriate provider for this tile, which we don't want in case the queue is full. This causes too much CPU and Memory load.
Related:  #757, probably also #801
This PR introduces a separation between `mapTileRequestFailed` and the new `mapTileRequestFailedExceedsMaxQueueSize` in:
- IMapTileProviderCallback.java
- MapTileModuleProviderBase.java
- MapTileProviderBase.java
- MapTileProviderArray.java
=> Handling tiles that failed due to max queue size being reached

osmdroid-android/src/main/java/org/osmdroid/util/PointL.java, osmdroid-android/src/main/java/org/osmdroid/util/RectL.java
New methods for `PointL` and `RectL` classes. These methods are currently not used by osmdroid itself, but may be utilized by users of the library.
`PointL`:
* `offset(dx,dy)`
`RectL`:
* `contains(x,y)`
* `inset(dx,dy)`
=> PointL and RectL method extensions

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/CustomPaintingSurface.java, osmdroid-android/src/main/java/org/osmdroid/util/LineBuilder.java, osmdroid-android/src/main/java/org/osmdroid/util/ListPointL.java, osmdroid-android/src/main/java/org/osmdroid/util/PathBuilder.java, osmdroid-android/src/main/java/org/osmdroid/util/SegmentClipper.java, osmdroid-android/src/main/java/org/osmdroid/views/Projection.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/LineDrawer.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polygon.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/milestones/MilestoneLister.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/milestones/MilestoneManager.java, osmdroid-android/src/test/java/org/osmdroid/util/ListPointLTest.java, osmdroid-android/src/test/java/org/osmdroid/util/SegmentClipperTest.java
Here are the improvements:
* for `Polyline` we now use `Canvas.drawLine` and we don't care about invisible segments: they may have an impact on visible Path but never on visible segments
* introduction of `ListPointL` as an optimization of `List<PointL>`, which is supposed to benefit both `Polyline` and `Polygon` display
New classes:
* `ListPointL`: an optimized version of `List<PointL>`
* `ListPointLTest`: a unit test class for `ListPointL`
* `LinearRing`: used new class `ListPointL` for constantly refreshed `List<PointL>`; handled the case where `mPath` is `null`; refactored a little
* `PathBuilder`: handled the case where `mPath` is `null`
* `Polyline`: removed the `Path` and handled the display with `Canvas.drawLine`
* `SegmentClipper`: added `boolean mPathMode`, to …
=> Optimized the display for `Polyline`

osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/NetworkAvailabliltyCheck.java
Having experienced a problem with unstable network conditions, where osmdroid tried to load tiles unavailingly instead of approximate them when there was no actual connectivity, I discovered that `NetworkAvailabliltyCheck` was checking for `NetworkInfo.isAvailable()` instead of `NetworkInfo.isConnected()` as advised here: https://developer.android.com/training/basics/network-ops/managing.html
> Note that you should not base decisions on whether a network is "available." You should always check isConnected() before performing network operations, since isConnected() handles cases like flaky mobile networks, airplane mode, and restricted background data.
=> Check for real network availabilty (connectivity) in NetworkAvailabliltyCheck

osmdroid-android/src/main/java/org/osmdroid/views/Projection.java
Some methods of the `Projection` class were mad public, so that users of the library can utilize them.
Furthermore two new methods for retrieving the projection offsets were added.
=> Make projection conversion methods public

osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/SimpleFastPointOverlay.java
SimpleFastPointOverlay layer when set with MAXIMUM_OPTIMIZATION (for displaying tens of thousands of points) had a redraw issue, in that the points were not correctly positioned during pinch zoom. This PR fixes the issue, making it feel smoother during pinch zooms.
=> Bug/#853 - improve redraw of SimpleFastPointOverlay

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-android/src/main/java/org/osmdroid/views/Projection.java
* `MapView`: refreshed the `mMapScroll*` members from the new `Projection` in case it had to adjust the offsets; not related to current issue: replaced calls to `requestLayout` (not appropriate) by `invalidate`
* `Projection`: created members `mScroll*` and their getters in order to store the initial `MapView` map scroll values and to give back to `MapView` the map scroll values after adjustments; created a private `adjustOffsets` method in order to compute new scroll values
=> Fixed bad map scrolling values when panning beyond the scrollable limits

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleSimpleFastPointOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/LabelledGeoPoint.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/SimpleFastPointOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/SimpleFastPointOverlayOptions.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/SimplePointTheme.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/StyledLabelledGeoPoint.java
Added class `StyledLabelledGeoPoint`, which allows to provide a style for each point and respective label individually. See `SampleSimpleFastPointOverlay` for a sample.
=> Feature/#855: added ability to individually style points and labels in SimpleFastPointOverlay, fixes #855

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleLimitedScrollArea.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-android/src/main/java/org/osmdroid/views/Projection.java, osmdroid-android/src/test/java/org/osmdroid/util/ProjectionTest.java
How is it possible?
Now you can add an `int extraSize` parameter when you set the scroll limits.
And if you use
* `mapView.getWidth()/2` for longitude extra size limit
* `mapView.getHeight()/2` for latitude extra size limit
you have enough flexibility to
* comply with the limits
* and set the map center to a `GeoPoint` within these limits
=> setCenter now able to work for every GeoPoint within the scroll limits

osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/DatabaseFileArchive.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/ZipFileArchive.java
As discussed in #688, it would be great to have all offline tile providers work in a way that tiles will be loaded regardless of their associated tile source name. `MBTilesFileArchive` and `GEMFFileArchive` have this behaviour by default.
This PR makes it possible for `DatabaseFileArchive` and `ZipFileArchive` to work the same way by introducing the new method `setIgnoreTileSource(boolean pIgnoreTileSource)` for both of them. When set true, the first available tile will be loaded regardless of the given tile source. (Default remains `false`)
=> Let DatabaseFileArchive and ZipFileArchive ignore the TileSource

osmdroid-android/src/main/java/microsoft/mappoint/TileSystem.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/LRUMapTileCache.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileCache.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBase.java, osmdroid-android/src/main/java/org/osmdroid/util/MapTileIndex.java, osmdroid-android/src/main/java/org/osmdroid/util/MapTileList.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/DefaultOverlayManager.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/MinimapOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/TilesOverlay.java, osmdroid-android/src/test/java/org/osmdroid/util/MapTileIndexTest.java, osmdroid-android/src/test/java/org/osmdroid/util/MapTileListTest.java
We could even have a cache capacity of 0!
How do we do that?
* just before drawing the tiles, we list them
* using that list, we specifically ask the cache not to remove the LRU tile if it's among the displayed tiles
Isn't using the LRU enough?
* apparently not (cf. #846)
* neither theoretically (cf. `MapTileApproximater` potential side effects)
Now that we have the current list of all displayed tiles, we can do more refined cache as @shiroyagi suggested ("introducing some hysteresis to reduce disk/network access")
=> Displayed tiles are now safely stored in memory

osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderArray.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBase.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
Based on what @roman-nevr proposed in #728, it is now possible to set an additional tiles scale factor for map scaling. This now works both for ScaledToDpi and standard size display.
Also removed redundant `MapTileProviderBase.clearTileCache()` from `MapTileProviderArray.detach()` and `MapView.detach()` and moved it to `MapTileProviderBase.detach()` where it should belong. Might be a fix for #776.
=>  Introducing an additional tiles scale factor and possible fix for #776

osmdroid-android/src/main/java/org/osmdroid/util/TileSystem.java, osmdroid-android/src/test/java/org/osmdroid/util/ProjectionTest.java
* `ProjectionTest`: added @Maradox's unit test method `test_conversionFromPixelsToPixels`; removed `delta` parameter in tests when possible
* `TileSystem`: fixed a side-effect in method `ClipToLong` ; deprecated now unused method `Clip`
=> Fixed a side effect on double-to-long conversions in TileSystem

osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileCache.java, osmdroid-android/src/main/java/org/osmdroid/util/MapTileList.java, osmdroid-android/src/main/java/org/osmdroid/util/MapTileListBorderComputer.java, osmdroid-android/src/main/java/org/osmdroid/util/MapTileListComputer.java, osmdroid-android/src/main/java/org/osmdroid/util/MapTileListZoomComputer.java, osmdroid-android/src/main/java/org/osmdroid/util/TileSystem.java, osmdroid-android/src/test/java/org/osmdroid/util/MapTileListBorderComputerTest.java, osmdroid-android/src/test/java/org/osmdroid/util/MapTileListTest.java, osmdroid-android/src/test/java/org/osmdroid/util/MapTileListZoomComputerTest.java, osmdroid-android/src/test/java/org/osmdroid/util/ProjectionTest.java
Not to be merged; this only the first step, though the goal is not very far:
* having a consistent default mode, similar to what we have now (displayed tiles and zooms +-1)
* making it easy to override this mode for explicit needs - for the moment we need to explicitly override `MapTileCache`'s constructor, and I'd prefer something smoother
New interface:
* `MapTileListComputer`: compute a map tile list from a map tile list source
New classes:
* `MapTileListBorderComputer`: compute a map tile list from a map tile list source: its border
* `MapTileListZoomComputer`: compute a map tile list from a map tile list source, on another zoom level
* `MapTileListBorderComputerTest`: unit test class for `MapTileListBorderComputer`
* `MapTileListZoomComputerTest`: unit test class for …
=> Added flexibility when computing tiles to be kept in memory cache

osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java, osmdroid-android/src/main/java/org/osmdroid/config/IConfigurationProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java, osmdroid-android/src/main/java/org/osmdroid/util/GarbageCollector.java, osmdroid-android/src/test/java/org/osmdroid/util/GarbageCollectorTest.java
New classes:
* `GarbageCollector`: running a task smoothly and asynchronously, only one execution at the same time
* `GarbageCollectorTest`: unit test class related to `GarbageCollector`
* `SqlTileWriter`: included index creation inside `runCleanupOperation` and one-by-one tile removal; replaced `runCleanupOperation` calls to garbage collection calls
=> Smooth tile garbage collection, with new SQL index

osmdroid-android/src/main/java/org/osmdroid/util/RectL.java, osmdroid-android/src/main/java/org/osmdroid/views/Projection.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polygon.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java
* `MyLocationNewOverlay`: replaced deprecated `Rect` and `Point` method calls from `Projection` by the `RectL` and `PointL` version
* `Projection`: fixed some javadoc comments; deprecated the version of `toProjectedPixels` still using `1E6 int` coordinates; added an explicit javadoc `@deprecated` comment for every `@Deprecated` annotation; removed useless private methods `getPixelXFromMercator`, `getPixelYFromMercator` and `getPixelFromMercator`; removed int/long duplicate code in the deprecated methods
* `RectL`: added methods `offset` and `union`, inspired from `Rect`'s, in order to be able to deprecate some `Projection` methods
=> Bug/#992: Refactored code and cleaned javadoc in class Projection

osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java
* `SqlTileWriter`: replaced the calls to `delete` and `insert` by a single call to `SQLiteDatabase.replace`
=> Feature/#974: faster database upsert for tiles

osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderArray.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileDownloader.java, osmdroid-android/src/main/java/org/osmdroid/util/Delay.java, osmdroid-android/src/test/java/org/osmdroid/util/DelayTest.java
When for some reason we could not get an up-to-date version of a tile, the tile fetch process went in an endless loop in the search of this up-to-date version.
The endless loop is not good itself, and it's even worse when there's a provider that uses the network: tons of useless network tries.
The fix is to consider that if we can't get the up-to-date version, we wait before trying again. And the delay is increasing.
New classes:
* `Delay`: successive delays container
* `DelayTest`: the unit test class around `Delay`
* `MapTileDownloader`: unrelated optimization regarding the instantiation of `TileLoader`; considered `UnknownHostException` as similar to other `IOException`s
* `MapTileProviderArray`: added member `mTileDelays` as a `Map<tile, Delay>` and an exponential …
=> bug/#989 - adding an increasing delay in tile fetch repetition

OpenStreetMapViewer/src/main/java/org/osmdroid/debug/model/SqlTileWriterExt.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java, osmdroid-android/src/main/java/org/osmdroid/util/DuringSplashScreen.java, osmdroid-android/src/main/java/org/osmdroid/util/SplashScreenable.java
A direct impact is that the app must be restarted in order to have a database path change taken into account.
* `SqlTileWriter`: `db_file` and `db` are now `static`; added a `static` lock used in the constructor; removed everything in `onDetach` as nobody should close a `static` database
=> bug/#1005 - SqlTileWriter now uses a static database, in order to avoid locks

osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileCache.java, osmdroid-android/src/main/java/org/osmdroid/util/MapTileList.java, osmdroid-android/src/test/java/org/osmdroid/util/MapTileListTest.java
* `MapTileCache`: in method `clear()` we don't try anymore to get the `mCachedTiles` map size outside of a `synchronized` block
* `MapTileList`: removed both constructors (we only use the default constructor now); handled the `mTileIndices == null` init case in all methods
* `MapTileListTest`: created method `testEmpty` about empty list side-effect
=> bug/#1012 - stronger code against not "synchronized" map access in "clear"

OpenStreetMapViewer/src/main/java/org/osmdroid/debug/model/SqlTileWriterExt.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java
It's now possible to count or delete tiles belonging to zoom levels or bounding boxes with only one SQL (very fast) query.
* `SqlTileWriter`: created a helper `getRowCount` method with where clause arguments; gently refactored; created a `getRowCount` method for bounding boxes; created methods `extractXFromKeyInSQL` and `extractYFromKeyInSQL` to enable SQL filters on X and Y (for a zoom level); create methods `getWhereClause` for bounding boxes SQL filters; created method `delete` for cache tile bounding box deletion; simplified method `exists`
* `SqlTileWriterExt`: simplified method `getRowCountExpired`; gently refactored
=> feature/#1019 - access to X and Y columns in cache database

osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderArray.java
To be called when something relevant happened (e.g. internet connectivity back on) in order to discard the previous delays and download without delay!
* `MapTileProviderArray`: created method `MapTileProviderArray.clearDelays`
=> New method in order to clear tile delays

osmdroid-android-it/src/main/java/org/osmdroid/TileSystemMathTest.java, osmdroid-android-it/src/main/java/org/osmdroid/views/OpenStreetMapViewTest.java, osmdroid-android/src/main/java/microsoft/mappoint/TileSystem.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderArray.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileApproximater.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileAssetsProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileDownloader.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileFileArchiveProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileFilesystemProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileSqlCacheProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/bing/BingMapTileSource.java, osmdroid-android/src/main/java/org/osmdroid/util/MapTileIndex.java, osmdroid-android/src/main/java/org/osmdroid/util/TileSystem.java, osmdroid-android/src/main/java/org/osmdroid/views/Projection.java, osmdroid-android/src/test/java/org/osmdroid/util/MapTileIndexTest.java, osmdroid-android/src/test/java/org/osmdroid/util/ProjectionTest.java, osmdroid-android/src/test/java/org/osmdroid/util/TileSystemTest.java
For the moment `microsoft.mappoint.TileSystem` and `org.osmdroid.TileSystemMathTest` are `Deprecated` and aren't used anymore.
They should be removed in the next "big-enough" version.
The following classes now fully use `org.osmdroid.util.TileSystem` instead of `microsoft.mappoint.TileSystem`:
* `MapTileApproximater`
* `MapTileAssetsProvider`
* `MapTileDownloader`
* `MapTileFileArchiveProvider`
* `MapTileFilesystemProvider`
* `MapTileIndex`
* `MapTileIndexTest`
* `MapTileProviderArray`
* `MapTileSqlCacheProvider`
* `OpenStreetMapViewTest`
* `Projection`
* `ProjectionTest`
* `BingMapTileSource`: removed useless import of `microsoft.mappoint.TileSystem`
* `microsoft.mappoint.TileSystem`: deprecated the class and everything inside; to be removed in the next main version
* …
=> feature/#111 - Getting rid of class microsoft.mappoint.TileSystem

osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileFileArchiveProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileFileStorageProviderBase.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileFilesystemProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileSqlCacheProvider.java
If ever a map tile provider deserves to fail because it needs the SD card and the SD card is not available, it will fail anyway.
And if it doesn't need the SD card, it won't be prevented from working correctly anymore by this "is SD card available?" check.
* `MapTileFileArchiveProvider`: removed calls to `isSdCardAvailable`
* `MapTileFileStorageProviderBase`: removed static member `mSdCardAvailable` and methods `checkSdCard` and `isSdCardAvailable`
* `MapTileFilesystemProvider`: removed call to `isSdCardAvailable`
* `MapTileSqlCacheProvider`: removed call to `isSdCardAvailable`
=> Removed the systematic and problematic "is SD card available?" check

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/BaseSampleFragment.java
When using concepts like `ViewPager`, the fragments are somehow accessed even when they are not fully created.
In the case of `BaseSampleFragment`, that means that we needed to handle the case when the `MapView` was not created when `onResume` or `onPause` were called.
````java
@Override
public void onPause(){
if (mMapView != null) { // added
mMapView.onPause();
} // added
super.onPause();
}
@Override
public void onResume(){
super.onResume();
if (mMapView != null) { // added
mMapView.onResume();
} // added
}
````
=> bug/#1030 - fixed NPE causing ANR

OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleWithTilesOverlayAndCustomTileSource.java
I explained how to make things work in my comments of issue #690, and I fixed the demo.
* `SampleWithTilesOverlayAndCustomTileSource`: added an explicit call to `setTileRequestCompleteHandler`
=> bug/#690 - secondary tile overlay does not refresh when tiles download

osmdroid-android/src/main/java/org/osmdroid/views/MapController.java
Thank you @InI4 for this bug fix suggestion.
* `MapController`: added an explicit call to `invalidate` after animation, in method `onAnimationEnd`
=> bug/#1040 - explicit call to invalidate after animation

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/bookmarks/BookmarkSample.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/IconPlottingOverlay.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleAnimateTo.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleZoomToBounding.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/milstd2525/MilStdPointPlottingOverlay.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/SampleAssetsOnlyRepetitionModes.java, osmdroid-android-it/src/main/java/org/osmdroid/views/OpenStreetMapViewTest.java, osmdroid-android/src/main/java/microsoft/mappoint/TileSystem.java, osmdroid-android/src/main/java/org/osmdroid/util/BoundingBox.java, osmdroid-android/src/main/java/org/osmdroid/util/TileSystem.java, osmdroid-android/src/main/java/org/osmdroid/util/TileSystemWebMercator.java, osmdroid-android/src/main/java/org/osmdroid/views/MapController.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-android/src/main/java/org/osmdroid/views/Projection.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Overlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/SimpleFastPointOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/util/PathProjection.java, osmdroid-android/src/test/java/org/osmdroid/util/BoundBoxTest.java, osmdroid-android/src/test/java/org/osmdroid/util/GeoPointTest.java, osmdroid-android/src/test/java/org/osmdroid/util/ProjectionTest.java, osmdroid-android/src/test/java/org/osmdroid/util/TileSystemTest.java, osmdroid-android/src/test/java/org/osmdroid/views/overlay/LinearRingTest.java, osmdroid-geopackage/src/main/java/org/osmdroid/gpkg/tiles/raster/GeoPackageMapTileModuleProvider.java, osmdroid-wms/src/main/java/org/osmdroid/wms/DomParserWms111.java
New class:
* `TileSystemWebMercator`: the current implementation of a tile system in a Web Mercator projection
* `BookmarkSample`: now uses getters for min/max latitude/longitude
* `BoundBoxTest`: now uses getters for min/max latitude/longitude
* `BoundingBox`: now uses getters for min/max latitude/longitude
* `DomParserWms111`: now uses getters for min/max latitude/longitude
* `GeoPackageMapTileModuleProvider`: now uses getters for min/max latitude/longitude
* `GeoPointTest`: now uses getters for min/max latitude/longitude and other non static `TileSystem` methods
* `IconPlottingOverlay`: now uses getters for min/max latitude/longitude
* `LinearRing`: impacted the `getCenter` method
* `LinearRingTest`: now uses getters for min/max latitude/longitude
* `MapController`: …
=> New projection systems: class TileSystem is now abstract and can be extended

osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileCache.java, osmdroid-android/src/test/java/org/osmdroid/tileprovider/MapTileCacheTest.java
Fix a race in `MapTileCache` (#1012).
This synchronizes a call to `mCachedTiles.remove`, the same way other calls are guarded.
As discussed on: https://github.com/osmdroid/osmdroid/issues/1012#issuecomment-391466140
=> bug/#1012 Add synchronization in MapTileCache.remove

OSMMapTilePackager/src/main/java/org/osmdroid/mtp/OSMMapTilePackager.java
Bug fix: runDownloading should not be called if packaging from a temp directory
(serverURL==null && tempFolder.exists())
=> Fix creating tilepackage from temp directory

GoogleWrapperSample/build.gradle, osmdroid-third-party/build.gradle
> A problem occurred configuring project ':GoogleWrapperSample'.
A problem occurred configuring project ':osmdroid-third-party'.
Could not find play-services.jar (com.google.android.gms:play-services:8.4.0).
Searched in the following locations:
https://jcenter.bintray.com/com/google/android/gms/play-services/8.4.0/play-services-8.4.0.jar
Impacted file:
* `build.gradle`: removed the line about play-services
=> osmdroid-third-party: build.gradle workaround about google play-services

osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileDownloader.java
New method `MapTileDownloader.computeExpirationTime(Long pHttpExpiresTime)` can be overridden in order to set specific expiration times.
* `MapTileDownloader`: added methods `private long computeExpirationTime(String pHttpExpiresHeader)` and overridable `protected long computeExpirationTime(Long pHttpExpiresTime)` in order to add flexibility; gently refactored
=> feature/#1044 : more flexibility for tile expiration

osmdroid-android/src/main/java/org/osmdroid/views/overlay/Marker.java
* `Marker`: now testing in method `hitTest` if `mIcon` is null to avoid rare cases of NPE
=> bug/#1078 - stronger hit test for Markers

.travis.yml, osmdroid-android-it/src/main/java/org/osmdroid/views/util/OpenStreetMapTileProviderDirectTest.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/BitmapPool.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/BitmapTileSourceBase.java
closes #1065 
So the problem was that on 10 < API < 19 the BitmapPool returned bitmaps for reuse without checking if size is identical, which is a hard requirement before API 19. This was unlikely to show up in production apps since most bitmaps are tiles which have identical sizes anyway.
With this change, we have to trust that the tilesize in the different `ITileSource`s is correct. Determining the size from the file or inputstream would add significant overhead.
=> #1065 Fix handling of reusable bitmaps

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tilesources/SampleLieFi.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderArray.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java
* `MapTileProviderArray`: deprecated method `isDowngradedMode()`; replaced it with method `isDowngradedMode(long pMapTileIndex)` that is able to take into account the zoom, x and y ranges of the providers
* `MapTileProviderBasic`: removed deprecated method `isDowngradedMode()`; replaced it with method `isDowngradedMode(long pMapTileIndex)` that takes into account the zoom range of the online providers
* `SampleLieFi`: replaced method `isDowngradedMode()` with `isDowngradedMode(long pMapTileIndex)`
=> bug/#1106 - extended "downgraded mode" to zoom range checks

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
I noticed these when upgrading from `5.6.5` to `6.0.2` and making use of some new functionality.
=> Some minor documentation fixes

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleAnimateTo.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
* `MapView`: created a new version of method `zoomToBoundingBox` with additional parameters `zoomFallback` (when no zoom can be computed for the given bounding box - typically for a single point bounding box) and `animationSpeed`, used the recent `MapController.animateTo` method, returned the computed zoom
* `SampleAnimateTo`: added 4 test examples at the beginning about bounding boxes and Manhattan (single point, single latitude, single longitude, normal); explicitly used `MapView.zoomToBoundingBox`; gently refactored
=> bug/#1116 - new "fallback zoom" option for MapView.zoomToBoundingBox

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
* `MapView`: edited method `zoomToBoundingBox` - renamed parameter `pZoomFallback` to a more explicit `pMaximumZoom`, slightly changed the code accordingly, added Javadoc, gently refactored
=> bug/#1116_2 - parameter purpose change in MapView.zoomToBoundingBox

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMarker.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMilitaryIconsMarker.java, osmdroid-android/src/main/java/org/osmdroid/util/TileSystem.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/DefaultOverlayManager.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Marker.java
In the process of fixing the initial issue, I optimized the code for Marker drawing, with the following results:
* drawing 5050 markers, all visible - with the latest optim: 130ms, with the old version: 204ms (55%)
* drawing 5050 markers, all visible - with the latest optim: 130ms, without the `BitmapDrawable optim`: 155ms (15%)
* drawing 5050 markers, all visible - with the latest optim: 130ms, without the `rotation==0` optim: 165ms (25%)
* drawing 5050 markers, only one actually visible - with the latest optim: 64ms, with the old version: 200ms (210%)
* `DefaultOverlayManager`: unrelated duplicate code fix in method `onDraw`
* `Marker`: added display helper members `mDisplayed`, `mRect` and `mOrientedMarkerRect`; created optimized display method `drawAt`; impacted …
=> bug/#516 - fixed Marker.hitTest with rotation and optimized drawing

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-android/src/main/java/org/osmdroid/views/MapViewRepository.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Marker.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polygon.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/infowindow/InfoWindow.java
New class:
* `MapViewRepository`: repository for a `MapView`, designed for "singleton-like" objects that need a clean detach
* `InfoWindow`: explicitly added in the constructor the `InfoWindow` to the `MapViewRepository`
* `MapView`: added a `MapViewRepository` member
* `Marker`: added a `MapViewRepository` member; replaced `static` members `mDefaultInfoWindow` and `mDefaultIcon` with `MapViewRepository.getDefaultMarkerInfoWindow` and `MapViewRepository.getDefaultMarkerIcon`; deprecated `static` method `cleanDefaults`; gently refactored
* `Polygon`: replaced `static` member `mDefaultInfoWindow` with `MapViewRepository.getDefaultPolygonInfoWindow`; gently refactored
* `Polyline`: replaced `static` member `mDefaultInfoWindow` with …
=> bug/#1074 - cleaner memory management (from static to instance variables)

osmdroid-android/src/main/java/org/osmdroid/util/Distance.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java, osmdroid-android/src/test/java/org/osmdroid/util/DistanceTest.java
Tested from zoom 0 to zoom 29: no drifting at all for Polyline info window bubbles.
* `Distance`: introduced the concept of "projection factor"; created methods `getSquaredDistanceToProjection`, `getProjectionFactorToLine` and `getProjectionFactorToSegment`; removed unused `private` method `crossProduct`; fixed comments
* `DistanceTest`: created method `test_getProjectionFactorToLine`
* `LinearRing`: created method `getCloseTo` for a precise touch computation; rewrote method `isCloseTo` build on `getCloseTo`
* `Polyline`: created method `getCloseTo` for a precise touch computation; rewrote method `isCloseTo` build on `getCloseTo`; impacted method `onSingleTapConfirmed` that now uses a `GeoPoint` that belongs to the `Polyline`
=> bug/#909 - Polyline info bubble is now anchored on the Polyline, not on the initial touch event

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleItemizedOverlayMultiClick.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMarkerMultiClick.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleWithMinimapItemizedOverlayWithFocus.java, osmdroid-android/src/main/java/org/osmdroid/util/GeoPoint.java
I created 2 new samples, to be found in "More Samples / Data": "Overlapping ItemizedOverlays' click" and "Overlapping Markers' click"
New classes:
* `SampleItemizedOverlayMultiClick`: Sample on how to handle a click on overlapping `OverlayItem`s, to be found in "More Samples / Data / Overlapping ItemizedOverlays' click"
* `SampleMarkerMultiClick`: Sample on how to handle a click on overlapping `Marker`s, to be found in "More Samples / Data / Overlapping Markers' click"
* `GeoPoint`: added a constructor with `IGeoPoint` as parameter
* `SampleFactory`: added the 2 new classes `SampleItemizedOverlayMultiClick` and `SampleMarkerMultiClick`
* `SampleWithMinimapItemizedOverlayWithFocus`: unrelated - used not-deprecated new versions of old methods
=> feature/#1122 - samples on how to handle a click on overlapping items

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleItemizedOverlayMultiClick.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMarkerMultiClick.java
* `SampleItemizedOverlayMultiClick`
* `SampleMarkerMultiClick`
=> feature/#1122 - removed the confusing animation at start of demos

osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java, osmdroid-android/src/main/java/org/osmdroid/util/TileSystem.java, osmdroid-android/src/main/java/org/osmdroid/util/TileSystemWebMercator.java, osmdroid-android/src/test/java/org/osmdroid/tileprovider/cachemanager/CacheManagerTest.java, osmdroid-android/src/test/java/org/osmdroid/util/MapTileAreaTest.java, osmdroid-android/src/test/java/org/osmdroid/util/TileSystemWebMercatorTest.java
New class:
* `TileSystemWebMercatorTest`: slightly unrelated unit test class about class `TileSystemWebMercatorTest`
* `CacheManager`: deprecated methods `getMapTileFromCoordinates` and `getCoordinatesFromMapTile` in favor of new `TileSystem` methods; replaced in method `getTilesCoverageIterable` an on-the-fly `IterableWithSize<Long>` class with an instance of `MapTileAreaList`; made `static` method `getTilesRect` `public`
* `CacheManagerTest`: created new test methods `testGetTilesRectSingleTile` and `testGetTilesRectWholeWorld`; used now `public` method `CacheManager.getTilesRect` in method `getTilesCoverage`
* `MapTileAreaTest`: slightly unrelated new `testCorners` method
* `TileSystem`: created methods `getTileXFromLongitude`, `getTileYFromLatitude`, …
=> feature/#1144 - using the new MapTileAreaList class in CacheManager (refactoring)

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleRace.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/CustomPaintingSurface.java
* `CustomPaintingSurface`: added a `Paint.Cap.ROUND` feature for all polylines
* `SampleRace`: added a `Paint.Cap.ROUND` feature for all polylines; unrelated - computed the initial bounding box
=> bug/#1164: fixed the broken segment joints for Polylines in demos

osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polygon.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java
* `LinearRing`: split member `mPrecomputed` in `mProjectedPrecomputed` and `mDistancePrecomputed`; split method `computeProjectedAndDistances` in `computeProjected` and `computeDistances`; created method `getDistance` that aggregates segment distances
* `Polygon`: created method `getDistance`
* `Polyline`: created method `getDistance`
=> feature/#1168 - Total distance of a Polyline or Polygon in meters

osmdroid-android/src/main/java/org/osmdroid/tileprovider/constants/OpenStreetMapTileProviderConstants.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/TileDownloader.java, osmdroid-android/src/test/java/org/osmdroid/tileprovider/modules/TileDownloaderTest.java
New class:
* `TileDownloaderTest`: unit test class for `TileDownloader`, especially regarding tile expiration computation
* `OpenStreetMapTileProviderConstants`: added constant `HTTP_CACHECONTROL_HEADER` (as `"Cache-Control"`)
* `TileDownloader`: now also uses the cache-control http header in tile expiration computation in method `downloadTile`; created helper methods `getHttpExpiresTime` and `getHttpCacheControlDuration` and modified method `computeExpirationTime` accordingly
=> bug/#1167 - using also http header cache-control:max-age for tile expiration

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tilesources/SampleLieFi.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java, osmdroid-geopackage/src/main/java/org/osmdroid/gpkg/tiles/raster/GeoPackageProvider.java
* `MapTileProviderBasic`: new `static` method `getMapTileFileStorageProviderBase` that fixes the possible inconsistency between the `IFilesystemCache` and the `MapTileFileStorageProviderBase`; used this method the constructor; unrelated constructor gentle refactoring
* `GeoPackageProvider`: used new `static` method `MapTileProviderBasic.getMapTileFileStorageProviderBase` in the constructor
* `SampleLieFi`: used new `static` method `MapTileProviderBasic.getMapTileFileStorageProviderBase` in `MapTileProviderLieFi`'s constructor
=> bug/#1172 - consistency between tile writer and tile provider

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
* `MapView`: added a version of method `setExpectedCenter` with offset parameters
=> feature/#1178 - MapView.setExpectedCenter with new offset parameters

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMarker.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Marker.java
* `Marker`: fixed the orientation computation in method `draw`
* `SampleMarker`: used a more orientation-obvious icon for better tests
=> bug/#1181 - correct orientation for marker icons on orientated maps

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/BaseSampleFragment.java, osmdroid-android/src/main/java/org/osmdroid/util/MapTileAreaZoomComputer.java, osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsController.java, osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsDisplay.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-android/src/test/java/org/osmdroid/util/MapTileAreaZoomComputerTest.java, osmdroid-android/src/test/java/org/osmdroid/views/CustomZoomButtonsDisplayTest.java
The `CustomZoomButtonsController` class replaces the use of `android.widget.ZoomButtonsController`:
* no more crash when the `MapView` is detached
* customizable display using method `getDisplay`, including icons and position
* customizable visibility using method `setVisibility` (display always / never / show and then fade out)
* customizable alpha animation when fading out
* handle short click and long click the same way, including when the map is rotated
New classes:
* `CustomZoomButtonsController`: controller of the zoom buttons, as a substitute for to-be-deprecated `android.widget.ZoomButtonsController`
* `CustomZoomButtonsDisplay`: display of the zoom buttons
* `CustomZoomButtonsDisplayTest`: unit test class for class `CustomZoomButtonsDisplay`
* `MapView`: replaced …
=> bug/#825 - new custom zoom controller

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
* `MapView`: put back the calls to method `ViewGroup.requestLayout` in methods `setZoomLevel`, `setMapOrientation`, `setPositionAndScale` and `setMapScroll`, as they used to be before #849, because of the impact on child views
=> bug/#1191 - put back the calls to ViewGroup.requestLayout

.travis.yml, OpenStreetMapViewer/build.gradle, OpenStreetMapViewer/src/main/AndroidManifest.xml, OpenStreetMapViewer/src/main/res/values/oss_licenses.xml, build.gradle, gradle.properties, osmdroid-android/src/main/AndroidManifest.xml, osmdroid-geopackage/build.gradle, osmdroid-geopackage/src/main/AndroidManifest.xml, osmdroid-mapsforge/build.gradle, osmdroid-mapsforge/src/main/AndroidManifest.xml, osmdroid-simple-map/build.gradle, osmdroid-wms/build.gradle, osmdroid-wms/src/main/AndroidManifest.xml, osmdroid-wms/src/test/java/org/osmdroid/wms/ParserTest.java
The recent commits concerning #1098 only covered part of the problem: Having compileSDK on a different version than the support libs is guaranteed to cause issues.
This PR brings the support lib up to version to 26.x. Please note that I just made sure this builds an the tests run - there still might be some issues due to the rather large jump and the corresponding behavior changes in various components of the support lib. Ideally someone should go through https://developer.android.com/topic/libraries/support-library/revisions and check the notes for possible issues. 
Most importantly this PR also raises the minSDK for the demo app to 14, since the 26.0 support libs require it.
=> Bug/#1098 - Bump support lib to 26

osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlayWithFocus.java
* `ItemizedOverlayWithFocus`: took into consideration the map orientation for the info window in method `draw`
=> bug/#994 - handle the map orientation for the info window of ItemizedOverlayWithFocus

osmdroid-android/src/main/java/org/osmdroid/util/BoundingBox.java, osmdroid-android/src/test/java/org/osmdroid/util/BoundingBoxTest.java
* to take into account the dateline
* clip out-of-bounds latitude
* wrap-around out-of-bounds longitude
=> BoundingBox: Rewrite increaseByScale()

osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsController.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
* `CustomZoomButtonsController`: slight unrelated edit - even when the zoom button is deactivated (_id est_ looks gray) a tap on it is caught, in order to prevent the case where someone frantically clicks on the zoom out button down to zoom 0 - when in zoom 0 a double click on the zoom out button is supposed to stay on zoom 0, not zoom in
* `MapView`: added the zoom button test in `MapViewDoubleClickListener.onDoubleTap`
=> bug/#1218 - added the zoom button test in map view double tap listener

OpenStreetMapViewer/src/main/java/org/osmdroid/debug/CacheAnalyzerActivity.java, OpenStreetMapViewer/src/main/java/org/osmdroid/debug/model/SqlTileWriterExt.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileCache.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java, osmdroid-android/src/main/java/org/osmdroid/util/MapTileArea.java
* `MapTileCache`: added the concept (member + setter) of "stressed memory" - when `true`, we systematically remove asap the useless tiles from the memory cache, when `false` (default value) we just remove enough tiles to fit the cache size, cf. method `garbageCollection`
* `MapTileProviderBasic`: explicitly defaulted the memory cache stressed memory parameter to `false`
* `SqlTileWriterExt`: slightly unrelated - added info about the tile sizes in method `getSources` and class `SourceCount`
* `CacheAnalyzerActivity`: slightly unrelated - added info about tile sizes in the display header, cf. method `run`
* `MapTileArea`: slightly unrelated - overrode `toString`
=> bug/#1217 - new "stressed memory" parameter in memory cache management

osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/SqlTileWriter.java
* `MapTileProviderBasic`: set the default `setAutoEnsureCapacity` to `false` (instead of `true`) because of alleged memory side-effect crash
* `SqlTileWriter`: refactored method `loadTile` - cleaner and optimized cursor management
=> bug/#1222 - SqlTileWriter.loadTile refactoring and memory side effect

osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileCache.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBase.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/TilesOverlay.java
There used to be an unexpected removal of tiles from cache when zooming out. Not only did I remove this impact on cache, but I also made it less likely to happen again by downgrading cache method `remove` from `public` to `protected`.
The rest is about code optimization when zooming in and out.
* `MapTileCache`: downgraded method `remove` from `public` to `protected`, in order to avoid undesired cache management from outside
* `MapTileProviderBase`: edited the "is it worth?" check at the beginning of method `rescaleCache` in order to avoid eventually unnecessary code and instance creations; removed the removal of tile from cache in `ZoomOutTileLooper.computeTile`
* `MapView`: optimized the call to `MapTileProviderBase.rescaleCache` using the new `Rect mRescaleScreenRect` …
=> bug/#1217_2 - zoom and cache management refactoring

osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlayWithFocus.java
* `ItemizedOverlayWithFocus`: fixed in method `draw` the drawing of the marker focused base
=> bug/#994_2 - fix of irrelevant drawing of focused base for ItemizedOverlayWithFocus

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleZoomToBounding.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-android/src/main/java/org/osmdroid/views/Projection.java
* `MapView`: fine-tuned a version of method `zoomToBoundingBox`, in order to have the bounding box always centered on the map
* `Projection`: upgraded a version of method `adjustOffsets` from "private" to "package-private"
* `SampleZoomToBounding`: animated the zoom; minor refactoring; added sample values for tests
=> bug/#1239 - fine-tuned center for zoomToBoundingBox / large latitude spans

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
If you don't use something like `MapView.setZoomLevel`:
* your map will be on zoom 0 - fair enough
* the zoom buttons need to be initialized - which was not the case, and both were inactive
* `MapView`: added an explicit call to `checkZoomButtons` in the constructor
=> bug/#1241 - enabling/disabling zoom buttons at MapView init time too

OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/Bug82WinDeath.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/CirclePlottingOverlay.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/IconPlottingOverlay.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/milstd2525/MilStdPointPlottingOverlay.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/SampleTileStates.java, osmdroid-android/src/main/java/org/osmdroid/views/Projection.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/CopyrightOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/DefaultOverlayManager.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/FolderOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/GroundOverlay2.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/IconOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlayWithFocus.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/MapEventsOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Marker.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/MinimapOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Overlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/OverlayManager.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/PathOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polygon.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/ScaleBarOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/TilesOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/compass/CompassOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/gestures/RotationGestureOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/DirectedLocationOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/SimpleLocationOverlay.java
Note: All tests are welcomed: do you still see your `Overlay`s without any problem?
Created method `Overlay.draw(Canvas, Projection)`, to be used and overridden rather than the now deprecated method `draw(Canvas, MapView, boolean)`.
Impacted interface:
* `OverlayManager`: created method `onDraw(Canvas, Projection)`, to be used and overridden rather than the now deprecated method `onDraw(Canvas, MapView)`
* `Overlay`: created method `draw(Canvas, Projection)`, to be used and overridden rather than the now deprecated method `draw(Canvas, MapView, boolean)`; gently refactored
* `Projection`: added getters `isHorizontalWrapEnabled`, `isVerticalWrapEnabled` and `getOrientation`
* `CirclePlottingOverlay`: removed useless overridden code of `draw(Canvas, MapView, boolean)` as …
=> feature/#990 - step 1 - Overlay.draw(Canvas, Projection)

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleAnimateToWithOrientation.java, osmdroid-android/src/main/java/org/osmdroid/api/IMapController.java, osmdroid-android/src/main/java/org/osmdroid/util/MyMath.java, osmdroid-android/src/main/java/org/osmdroid/views/MapController.java, osmdroid-android/src/test/java/org/osmdroid/util/MyMathTest.java
New classes:
* `MyMathTest`: unit test class for `MyMath`, more specifically for its new `getAngleDifference` method
* `SampleAnimateToWithOrientation`: demo around the new `Boolean pClockwise` parameter of `MapController.animateTo`, to be found in "More Samples / Events / Animate To With Orientation"
* `MapController`: created a new version of method `animateTo` that includes the new "clockwise" parameter; fixed minor omissions
* `MyMath`: created method `cleanPositiveAngle` that returns the same angle modulo 360 degrees between 0 and 360; create method `getAngleDifference` as a helper to know which way one should go between two angles
* `SampleFactory`: included the new `SampleAnimateToWithOrientation` demo
Impacted interface:
* `IMapController`: added the new version …
=> bug/#1256 - added a "clockwise" parameter in method MapController.animateTo

osmdroid-android/src/main/java/org/osmdroid/views/MapController.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java
_Do I need to open an issue?_
When the "follow location" option is enabled and "auto stop" feature is enabled too, then when the user tries to scroll the map it causes a weird lag before performing the actual map pan based on user input.
`MyLocationNewOverlay`'s `onTouchEvent` doesn't stop the animation coming from `setLocation` method. Controller doesn't end it's scroller animation even if it is supposed to do so.
Make `onTouchEvent` stop the map animation on `ACTION_DOWN` and fix `MapController` to actually end the animation.
`MapController`'s `stopAnimation` comments are not clear for me. The animator is not only for zoom but for scroll too.
- Device with Android 9.0
- Device with Android 4.4
- Sample osmdroid app: More samples -> Location -> Follow Me
=> Fix scroll lag when "follow location" is cancelled by user input

osmdroid-android/src/main/java/org/osmdroid/views/overlay/DefaultOverlayManager.java, osmdroid-android/src/test/java/org/osmdroid/views/overlay/DefaultOverlayManagerTest.java
New class:
* `DefaultOverlayManagerTest`: unit test for `DefaultOverlayManager`
* `DefaultOverlayManager`: wrote a more robust construction of the `ListIterator<Overlay>` in method `overlaysReversed`, using new method `bulletProofReverseListIterator`
=> bug/#1260 - bullet-proof reverse order for DefaultOverlayManager

osmdroid-mapsforge/build.gradle, osmdroid-mapsforge/src/main/java/org/osmdroid/mapsforge/MapsForgeTileSource.java
Impacted files:
* `MapsForgeTileSource.java`: removed the call to `ReadBuffer.setMaximumBufferSize` in `createInstance`
* `osmdroid-mapsforge/build.gradle`: now using version `0.10.0` of mapsforge
=> bug/#1265 - switching to mapsforge 0.10.0 (from 0.8.0)

OpenStreetMapViewer/src/main/java/org/osmdroid/StarterMapFragment.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
So far `MapView.onDetach` was systematically called in `MapView.onDetachedFromWindow`, which could cause problems when the view was detached from the window but not to be destroyed (in rare cases).
Now we have a `boolean` that says if we should call it. The default value is `true` for code legacy reasons.
The correct way is now something like:
````java
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
// ...
mMapView.setDestroyMode(false);
}
@Override
public void onDestroyView() {
super.onDestroyView();
mMapView.onDetach();
}
````
* `MapView`: new `boolean` member `mDestroyModeOnDetach` with a setter; impacted method `onDetachedFromWindow` accordingly; minor refactoring
* `StarterMapFragment`: added an explicit …
=> bug/#1247 - new `MapView.setDestroyMode` feature

osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileDownloader.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/OnlineTileSourceBase.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/XYTileSource.java
* `MapTileDownloader`: added an "acquire/release" mechanism in method `TileLoader.downloadTile`; gentle refactoring
* `OnlineTileSourceBase`: creation of a new constructor with the max concurrent parameter; added a `Semaphore` member; added methods `acquire` and `release` in order to implement the semaphore mechanism
* `TileSourceFactory`: added the parameter of maximum 2 concurrent accesses for tile source `MAPNIK`
* `XYTileSource`: creation of a new constructor with the max concurrent parameter; gentle refactoring
=> feature/#1278 - using a Semaphore when accessing online tile sources

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleCacheDownloaderArchive.java, osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/TileDownloader.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/OnlineTileSourceBase.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourcePolicy.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourcePolicyException.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/XYTileSource.java
New classes:
* `TileSourcePolicy`: tile source usage policy, including the max number of concurrent downloads, if it accepts a meaningless user agent, and if it accepts bulk downloads
* `TileSourcePolicyException`: `RuntimeException` dedicated to the enforcement of online tile source usage policies (`TileSourcePolicy`)
* `CacheManager`: the constructors now throw `TileSourcePolicyException` if the online tile source doesn't accept bulk downloads
* `DefaultConfigurationProvider`: created the static member `DEFAULT_USER_AGENT` in order to store the default user agent (if the actual user agent equals that default value, enforcement of some tile source policies will reject the downloads for this tile source)
* `OnlineTileSourceBase`: added a `TileSourcePolicy` member and its …
=> feature/#1289 - online tile source usage policy enforcement, particularly for MAPNIK

osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java, osmdroid-android/src/main/java/org/osmdroid/config/IConfigurationProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTilePreCache.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/TileDownloader.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourcePolicy.java
… for MAPNIK
Around `TileSourcePolicy`:
* "normalized" user agent (package name + "/" + version)
* disabling preventive download
* `DefaultConfigurationProvider`: new member `String mNormalizedUserAgent` and its getter; new method `computeNormalizedUserAgent(Context)` to compute its value
* `IConfigurationProvider`: added method `String getNormalizedUserAgent()`
* `MapTilePreCache`: added a check in method `search` - if the tile source policy says "we don't try to preventively download tiles", there won't be any download attempt
* `MapTileProviderBasic`: added the `MapTileDownloader` in the pre-cache tile providers
* `TileDownloader`: in `downloadTile`, uses the normalized user agent if the tile source policy says so
* `TileSourceFactory`: edited the `TileSourcePolicy` …
=> feature/#1289_2 - normalizing user agent and disabling preventive downloads

OpenStreetMapViewer/src/main/AndroidManifest.xml, OpenStreetMapViewer/src/main/res/xml/network_security_config.xml, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java
Impacted files:
* `OpenStreetMapViewer:AndroidManifest.xml`: added a reference to new config file `res/xml/network_security_config.xml`
* `OpenStreetMapViewer:res/xml/network_security_config.xml`: whitelisting of "http only" (and not "httpS") tile providers
* `osmdroid:TileSourceFactory`: whenever possible, switched the "http" tile providers into "https"
=> bug/#1287 - Android 9 - handling "http only" (not "httpS") tile providers

OpenStreetMapViewer/src/main/java/org/osmdroid/StarterMapFragment.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleWithTilesOverlayAndCustomTileSource.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
We temporarily roll back to the standard Android zoom buttons, as the default zoom controller.
If a developer wants to switch to the new custom zoom buttons, `mMapView.getZoomController()` must explicitly be called, in something like `mMapView.getZoomController().setVisibility(CustomZoomButtonsController.Visibility.SHOW_AND_FADEOUT)`.
* `MapView`: partial roll back to the standard Android zoom controller - the custom zoom controller is still there, but is silent (default behavior)
* `SampleWithTilesOverlayAndCustomTileSource`: removed a useless zoom control code (which is already the default mode)
* `StarterMapFragment`: removed a useless zoom control code (which is already the default mode)
[actually, a desperate attempt to PR a code that github just ignored]
=> Bug/#1299 2 - partial rollback of the custom zoom buttons

osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java
* `CacheManager`: the "supports bulk download?" check is now performed only for download actions
=> bug/#1316 - CacheManager little bug fix regarding bulk download support check timing

osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlayWithFocus.java
I also handle newline + wrap.
Extra test cases I used:
```java
String description1 = "Line1\nLine2\nLine3\nLine4\nLine5\nLine6\nLine7\nLine8\nLine9\nLine10\nLine11\nLine12\nLine13\nLine14\nLine15";
String description2 = "Line01 Line02 Line03 Line04 Line05 Line06 Line07 Line08 Line09 Line10 Line11 "
+ "Line12 Line13 Line14 Line15 Line16 Line17 Line18 Line19 Line20 Line21 Line22 Line23";
String description5 = "Line1Line2Line3Line4Line5Line6Line7Line8Line9Line10Line11Line12Line13Line14Line15line16line17line18line19line20line21line22line23line24line25line26line27line28line29line30";
String description6 = "01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789";
String …
```
=> Fix #1322: ItemizedOverlayWithFocus crash when very long description having no space

osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.java
This is meant to avoid the crash reported in #1368.
=> Fix an NPE found in a crash report.

osmdroid-android/src/main/java/org/osmdroid/views/MapController.java
Fix for https://github.com/osmdroid/osmdroid/issues/1299
fix StackOverflow, because when zooming in with zoom buttons,
osm tries to keep the map centered to the current user location.
See: org.osmdroid.views.overlay.mylocation.MyLocationNewOverlay.onSnapToItem
=> bug #1299: Zoom Button Crash in 6.1.0

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMarker.java, osmdroid-android/src/main/java/org/osmdroid/util/constants/GeoConstants.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/ScaleBarOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/ScaleDiskOverlay.java, osmdroid-android/src/main/res/values/strings.xml
A demo can be found in the "More Samples / Data / Marker" demo.
New class:
* `ScaleDiskOverlay`: displays a disk of a given radius (distance) around a GeoPoint
Impacts:
* `GeoConstants`: added `enum UnitOfMeasure`; gently refactored
* `ScaleBarOverlay`: refactored the display of scale text, in order to be reused in `ScaleDiskOverlay`
* `strings.xml`: created `format_distance_only_%` and `format_distance_value_unit`
* `SampleMarker`: added a `ScaleDiskOverlay` for each POI
=> feature/#1346 - new ScaleDiskOverlay class

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMapSnapshot.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleMapCenterOffset.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-android/src/main/java/org/osmdroid/views/Projection.java, osmdroid-android/src/test/java/org/osmdroid/util/ProjectionTest.java
The map center used to be projected into the screen center.
Now we have a possible offset from the screen center; default offset is [0, 0].
New class:
* `SampleMapCenterOffset`: demo about the new `MapView.setMapCenterOffset` method - demo that can be reached at "More Samples / Events / Animate To with Map Center Offset"
* `MapView`: created `int` members `mMapCenterOffsetX` and `mMapCenterOffsetY` with getters and a common setter; used it when constructing a new related `Projection`
* `Projection`: created `final int` members `mMapCenterOffsetX` and `mMapCenterOffsetY`; added these parameters to constructors; impacted accordingly methods `getScreenCenterX` and `getScreenCenterY`; gently refactored
* `SampleFactory`: added the new `SampleMapCenterOffset` demo
* …
=> feature/#1294_2 - new MapView.setMapCenterOffset method

OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/Bug382Crash.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/HeatMap.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleMilestonesNonRepetitive.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleOsmPath.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleRace.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/CustomPaintingSurface.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/SampleDrawPolylineAsPath.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/MarkerDrag.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/events/SampleZoomToBounding.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/milstd2525/MilStdMultipointOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/PolyOverlayWithIW.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polygon.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/gridlines/LatLonGridlineOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/gridlines/LatLonGridlineOverlay2.java, osmdroid-geopackage/src/main/java/org/osmdroid/gpkg/overlay/OsmMapShapeConverter.java
New classes:
* `PolyOverlayWithIW`: extending `OverlayWithIW`, extended by both `Polyline` and `Polygon` given the number of common methods
* `SampleDrawPolylineAsPath`: sample similar to `SampleDrawPolyline`, but where `Polyline`s are drawing in the "path" mode (and not in the "lines" mode)
* `CustomPaintingSurface`: created mode `PolylineAsPath`; put alpha in the color in order to see the vertices for `Polyline`s
* `LinearRing`: added the `boolean` member `mClosed` in order to make both `Polyline` and `Polygon` draw using a `Path`; new constructor for `Path` with a `boolean pClosed` parameter; taking into account the `mClosed` member when building the `Path`
* `SampleFactory`: added `SampleDrawPolylineAsPath` just after `SampleDrawPolyline`
* `Polygon`: now extends new …
=> bug/#1280 - possibility to draw Polylines using Path

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleSpeechBalloon.java, osmdroid-android/src/main/java/org/osmdroid/util/MyMath.java
* `MyMath`: unrelated new precision in the javadoc of method `computeCirclePoint`
* `SampleSpeechBalloon`: removed all the `Timer` feature, which was irrelevant for the very demo and caused crashes in the demo app; minor refactoring
=> bug/#1407 - simplified "speech balloon" demo

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/SampleFactory.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/SampleUnreachableOnlineTiles.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTilePreCache.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileApproximater.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileModuleProviderBase.java
New class:
* `SampleUnreachableOnlineTiles`: demo checking if the zoom restriction for tiles is correctly applied, to be found under "More Samples / Tileproviders / Zoom Restricted Online Tiles (14-15)"
* `MapTileApproximater`: called new method `TileLoader.loadTileIfReachable` instead of `TileLoader.loadTile`
* `MapTileModuleProviderBase`: new method `isTileReachable`; new method `TileLoader.loadTileIfReachable`, to be called instead of direct calls to `TileLoader.loadTile`
* `MapTilePreCache`: called new method `TileLoader.loadTileIfReachable` instead of `TileLoader.loadTile`
* `SampleFactory`: added new demo `SampleUnreachableOnlineTiles`
=> bug/#1416 - additional zoom check before tile download

OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/WeathForceActivity.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/AsyncTaskDemoFragment.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/layouts/SampleSplitScreen.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/layouts/rec/CustomRecycler.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/location/SampleFollowMe.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/location/SampleHeadingCompassUp.java, osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsController.java, osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsDisplay.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java, osmdroid-android/src/test/java/org/osmdroid/util/GarbageCollectorTest.java
* `AsyncTaskDemoFragment`, `CustomRecycler`, `SampleFollowMe`, `SampleHeadingCompassUp`, `SampleSplitScreen`, `WeathForceActivity`: removed a useless call to now deprecated method `MapView.setBuiltInZoomControls`, which used to be the default behavior anyway
* `MapView`: removed all the references on the deprecated Android zoom controls; moved the calls to zoom control test in `dispatchTouchEvent`; deprecated method `setBuiltInZoomControls`; unrelated minor refactoring
* `CustomZoomButtonsController`: made `public` method `isTouched` which uses new method `CustomZoomButtonsDisplay.isTouched`; deprecated method `onSingleTapConfirmed` and `onLongPress`
* `CustomZoomButtonsDisplay`: deprecated method `isTouchedRotated` as we now check the touch event before applying the …
=> feature/#1418 - custom zoom refactoring while removing the old standard zoom controllers

osmdroid-mapsforge/src/main/java/org/osmdroid/mapsforge/MapsForgeTileSource.java
Adds an optional language paramter to MapsForgeTileSource. This allows to set a prefered language for labels, which in most cases default to the map location's local language.
This sets one language for all map sources. Theoretically it is possible to set a prefered language per map source. I left this out for 1) simplicity and 2) because I don't see much use for this.
Fixes #1420
=> Add optional language parameter to MapsForgeTileSource

gradle/wrapper/gradle-wrapper.properties
The server services.gradle.org does no longer allow non-https downloads (see https://blog.gradle.org/decommissioning-http).
According to the gradle blog entry we are currently in the phase "November 14th, 2019 | Disable HTTP for 24 hours and permanently drop support for TLSv1."
Therefore it is required to update the gradle url to https.
=> fix for osmdroid broken ci system: update gradle download url to https

osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/bing/BingMapTileSource.java
The Bing maps authentication URL that is used for sending the application's Bing Maps Key to Microsoft was still using unencrypted HTTP, instead of HTTPS. 
I have verified that the URL via HTTPS works as expected, it was correctly returning a valid response using my personal Bing Maps key for the imagery-set "Road".
=> Bing map upgrade authentication and tile URL to https

OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/BugFactory.java, OpenStreetMapViewer/src/main/java/org/osmdroid/bugtestfragments/Issue1444.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/ItemizedOverlayWithFocus.java
* `ItemizedOverlay`: set back the correct icon bounds after they were changed for the display part
=> bug/#1444 - setting back the correct icon bounds in ItemizedOverlay

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
Just cause it came along while I was doing that scroll button thing. This fixes it for my device: When you fling the motion stays all in one direction, regardless of the actual rotation of the map.
=> Fixed fling: The velocity vector needed some (un-)rotation.

osmdroid-android/src/main/java/org/osmdroid/views/overlay/DefaultOverlayManager.java
* `DefaultOverlayManager`: edited `onDrawHelper`
=> bug/#1462 - removed the call to BoundingBox.overlaps that ignores rotation

osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/SimpleFastPointOverlay.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/SimpleFastPointOverlayOptions.java
and one to SimpleFastPointOverlay.  This is to facilitate deriving/customizing SimpleFastPointOverlay.drawPointAt
=> feature/osmdroid#1472 - add getters to SimpleFastPointOverlayOptions

osmdroid-android/src/main/java/org/osmdroid/util/SideOptimizationPointAccepter.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java, osmdroid-android/src/test/java/org/osmdroid/util/SideOptimizationPointAccepterTest.java
New classes:
* `SideOptimizationPointAccepter`: `PointAccepter` that simplifies the list of consecutive points with the same X or Y
* `SideOptimizationPointAccepterTest`: Unit test class for `SideOptimizationPointAccepter`
* `LinearRing`: used a `SideOptimizationPointAccepter` on top of the `PathBuilder` (which will get only a simplified point list)
=> feature/#1467 - Simplifying the list of consecutive points for Path

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/SampleShapeFile.java, osmdroid-android/src/main/java/org/osmdroid/util/ListPointAccepter.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/PolyOverlayWithIW.java
If the poly is smaller (in pixels) than size1, draw a precomputed simplified list of segments.
If it's even smaller (than size2), draw even faster the poly as a rectangle.
Of course this is only optional; the default being to always display the regular poly.
The demo is included in `SampleShapeFile`, and the important methods here are `setDowngradeDisplay` and `setDowngradePixelSizes`.
New class:
* `ListPointAccepter`: a `PointAccepter` that builds a `List` of `PointL` as a list of long, long
* `LinearRing`: new members `mProjectedWidth` and `mProjectedHeight`; new method `computeDowngradePointList` that computes the list of points of a polyline that would be the projection of the GeoPoints on a centered size*size square; new method `resetPrecomputations`
* …
=> feature/#1480 - new method PolyOverlayWithIW.setDowngradePixelSizes

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/CustomPaintingSurface.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/PolyOverlayWithIW.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polygon.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java
* `CustomPaintingSurface`: now using the new `PolyOverlayWithIW.usePath(boolean)` method for the "Polyline as Path" demo
* `Polygon`: moved methods `contains` and `onSingleTapConfirmed` to `PolyOverlayWithIW`; implements new method `PolyOverlayWithIW.click(MapView,GeoPoint)`
* `Polyline`: removed erroneous member `mDensity`; moved member `mDensityMultiplier` (with setter) and methods `isCloseTo`, `getCloseTo` and `onSingleTapConfirmed` to `PolyOverlayWithIW`; implements new method `PolyOverlayWithIW.click(MapView,GeoPoint)`
* `PolyOverlayWithIW`: new abstract method `PolyOverlayWithIW.click(MapView,GeoPoint)`; created method `usePath(boolean)` in order to set the path mode even after the addition of GeoPoints; moved methods from `Polygon` and `Polyline`
=> feature/#1458 - new method `PolyOverlayWithIW.usePath`

osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsDisplay.java
Custom map zoom buttons should zoom only when touched but not when finger slides across them.
=>  bug/#1471 - zoom buttons should zoom only when touched 

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/drawing/ShowAdvancedPolylineStyles.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/advancedpolyline/ColorMappingRanges.java
* `ColorMappingRanges`: added a strict comparison boolean parameter to the constructor
* `ShowAdvancedPolylineStyles`: impacted the call to `ColorMappingRanges` constructor
=> feature/#1378_3 - comparison for ColorMappingRanges can be strict or not

OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleWithTilesOverlay.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/IMapTileProviderCallback.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileApproximater.java, osmdroid-android/src/main/java/org/osmdroid/views/overlay/DefaultOverlayManager.java
* `DefaultOverlayManager`: unrelated minor fix
* `IMapTileProviderCallback`: unrelated minor refactoring
* `MapTileApproximater`: Android bug fixes for method `getTileBitmap` - when we get a bitmap from the pool, now we explicitly make it totally transparent
* `SampleWithTilesOverlay`: minor changes - `TileSourceFactory.PUBLIC_TRANSPORT`, `setLoadingBackgroundColor(Color.TRANSPARENT)` - in order to be able to reproduce the bug more easily if needed
=> bug/#1509 - Android bug fixes for MapTileApproximater and transparent images

osmdroid-android/src/main/java/org/osmdroid/views/overlay/FolderOverlay.java
=> bug/#1521 - default bounds for empty FolderOverlay

osmdroid-android/src/main/java/org/osmdroid/views/overlay/LinearRing.java
* `LinearRing`: edited method `setClipArea` in order to double the radius of the clip area
=> bug/#1528 - larger clip area for Polylines and Polygons

OpenStreetMapViewer/build.gradle
Impacted file:
* `build.gradle` (OpenStreetMapViewer): upgraded LeakCanary version to 2.2 (from 2.0) and minor refactoring
=> feature/#1545 - LeakCanary version upgrade to 2.2

osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/TileDownloader.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java
Try to enable TLSv1.2 and disable SSLv3 on SSLSockets, to prevent failing connections on older android versions and modern servers
Can be tested with newly added wikimedia tilesource
=> Bug/#1554 - add proxy for SSLSocketFactory to improve compatibility

OpenStreetMapViewer/src/main/java/org/osmdroid/PreferenceActivity.java, OpenStreetMapViewer/src/main/java/org/osmdroid/diag/DiagnosticsActivity.java, OpenStreetMapViewer/src/main/java/org/osmdroid/intro/StoragePreferenceFragment.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/cache/SampleAlternateCacheDir.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/geopackage/GeopackageFeatureTiles.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/geopackage/GeopackageFeatures.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/geopackage/GeopackageSample.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/MapsforgeTileProviderSample.java, osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java, osmdroid-android/src/main/java/org/osmdroid/config/IConfigurationProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/util/StorageUtils.java, osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
#1512 
Basically a complete overhaul of StorageUtils:
- lot's of refactoring
- < API19: Behaviour is untouched except fixing a minor bug, that lead to non-writable locations returned as writable
- 19 <= API < 29: legacy behaviour + additional storage locations when a context is provided
- \>API29: Only new behviour with fallback for targetSdk < API29 apps on >API29 devices.
- replacing references to now deprecated methods to the new alternatives.
On API29 and above a valid storage location can only be retrieved when a context is available. Therefore a hacky workaround has been implemented in MapView. This should cover most naive usages of the library.
In more advanced cases (e.g. own `MapTileModuleProviderBase` implementations) this can still lead to problems if the storage detection via …
=> Bug/#1512 - Storage location on API29 and above

osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java, osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/MapTileFileArchiveProvider.java
When I disable Storage (and before asking for permissions in the same Activity) I would be getting
```
java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.osmdroid.tileprovider.util.StorageUtils$StorageInfo.path' on a null object reference
```
=> fix crash if no storage permission

osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/TileDownloader.java
Fix Stackoverflow exceptions due to number of sockets created
@spyhunter99 This should be considered a hotfix as it fixes a critical bug on API <= 19 with encrypted connections.
=> Only set CompatiblitySocketFactory once

osmdroid-android/src/main/java/org/osmdroid/config/DefaultConfigurationProvider.java
Should fix #1621 as it covers cornercases where prefs exist, but there is no saved directory.
=> Use context for discovering cache dir also when prefs already exist

osmdroid-android/src/main/java/org/osmdroid/views/MapView.java
Fixes #1612 for all tested devices < Android 9 or > Android 9 and for **some** tested Android 9 devices.
I claim, that the Android 9 devices which now "bounce" are a minority, I have no idea how to figure what is the difference.
=> Fixed bouncing fling in bug/#1612.

osmdroid-android/src/main/java/org/osmdroid/views/Projection.java
The bounding box will now accommodate for rectangular screens being rotated throughout 360 degrees.
=> Apply screen rotation before calculating the bounding box

osmdroid-android/src/main/java/org/osmdroid/views/overlay/mylocation/DirectedLocationOverlay.java
Fixes drawing accuracy circle in dependent of point's lattitude
By default accuracy circle is drawing with reference to equator. If your geo point is above or below equator, accuracy circle drawing incorrect. Changes of this commit allow to draw correct circle with radius binded to point lattitude.
=> Fixes drawing accuracy circle

osmdroid-geopackage/src/main/java/org/osmdroid/gpkg/overlay/OsmMapShapeConverter.java
Use of polygonOptions's subtitle instead of polylineOptions's subtitle in toPolyline method of OsmMapShapeConverter
=> Wrong options object in Polyline conversion

osmdroid-mapsforge/src/main/java/org/osmdroid/mapsforge/MapsForgeTileSource.java
As discussed in this #1764 issue, osmdroid-mapsforge plugin could provide max zoom as it is provided by osmdroid plugin. 
Currently, when using osmdroid with mapsforge we are limited to use max zoom as 20 because of this [lower constant value](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-mapsforge/src/main/java/org/osmdroid/mapsforge/MapsForgeTileSource.java#L39) and not able to use max zoom as 29 which is provided from osmdroid. 
As discussed in the issue, I tested if the osmdroid-mapsforge plugin can work with max zoom = 29 and it works perfectly.
=> Changed osmdroid-mapsforge MAX ZOOM value to 29

osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsDisplay.java
This fixes issue #1733. I tested this by building the osmdroid-android project and manually loading the resulting library into my app. The unwanted behavior described in #1733 is gone: Only one zoom takes place when I tap long on the zoom in or out button.
=> Only zoom in/out on ACTION_UP event

README.md
compile is deprecated from new version of graddle
=> change compile to implementation

OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/geopackage/GeopackageFeatureTiles.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/geopackage/GeopackageFeatures.java, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/OfflinePickerSample.java, osmdroid-geopackage/build.gradle, osmdroid-geopackage/src/main/java/org/osmdroid/gpkg/overlay/OsmMapShapeConverter.java, osmdroid-geopackage/src/main/java/org/osmdroid/gpkg/overlay/features/OsmDroidMapShape.java, osmdroid-geopackage/src/main/java/org/osmdroid/gpkg/tiles/feature/GeopackageFeatureTilesOverlay.java, osmdroid-geopackage/src/main/java/org/osmdroid/gpkg/tiles/raster/GeoPackageMapTileModuleProvider.java, osmdroid-geopackage/src/main/java/org/osmdroid/gpkg/tiles/raster/GeoPackageProvider.java
#1707 
#1684 
#1706 
Looking to update the NGA-Geopackage libraries within OSMDroid to the latest versions.
=> Updated NGA GEOPackage core from 2.0.1 to 6.5.0

osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/MapBoxTileSource.java
According to the MapBox raster images API docs here: https://docs.mapbox.com/api/maps/raster-tiles/
The url for this api has changed to
https://api.mapbox.com/v4/{tileset_id}/{zoom}/{x}/{y}{@2x}.{format}
=> Fix Mapbox rester image api url. Add support for hightDPI.

osmdroid-android/src/main/java/org/osmdroid/tileprovider/tilesource/TileSourceFactory.java
"a.", "b.", "c." are not needed anymore, cf. https://github.com/openstreetmap/operations/issues/737
=> Upgrade to "tile.openstreetmap.org"

OpenStreetMapViewer/src/main/res/layout/intro_tilesources_osm.xml
* Fix a few places in the tilesource info text that referenced OpenStreetMap, but misspelled its name.
* Update the project's URL to the HTTPS version, and use the main domain "openstreetmap.org" (instead of "openstreetmaps.org" which is a non-HTTPS redirect to the proper site).
=> Fix #1924, use correct spelling of "OpenStreetMap"

OpenStreetMapViewer/build.gradle, OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/MapsforgeTileProviderSample.java, osmdroid-mapsforge/build.gradle, osmdroid-mapsforge/src/main/java/org/osmdroid/mapsforge/MapsForgeTileSource.java
Issue: MapsForge roads are too thick.
Setting UserScaleFactor for MapsForge with a value of .5F generates map tiles that more closely resemble that of a native MapsForge basic map with the same theme and .map. Roads are not too thick.
=> feature/ enable editing UserScaleFactor for generating MapsForge tiles

osmdroid-android/src/main/java/org/osmdroid/util/BoundingBox.java
Implements `equals` and `hashCode` for the `BoundingBox`  class.
=> Implement equals and hashCode for BoundingBox

osmdroid-mapsforge/src/main/java/org/osmdroid/mapsforge/MapsForgeTileSource.java
This commit adds the ability to create a MapsForgeTileSource from a FileInputStream. This should add the ability to use MapsForgeTileSource with files coming from Android's new(ish) [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider). It leverages the fact that MapFile also has a constructor that accepts a FileInputStream. See issue #1950
=> Create a MapsForgeTileSource from a FileInputStream

osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsController.java, osmdroid-android/src/main/java/org/osmdroid/views/CustomZoomButtonsDisplay.java
Please check carefully.
It fixes #1822 for me, but I did never experience the issue mentioned in #1775.
=> Fixing bug/#1822 avoiding recreation of bug/#1775.
